#!/usr/bin/env python3
"""
C-CoderDBC GUI
==============
A graphical interface that generates C pack/unpack code from DBC CAN matrix
files directly through the *cantools* library — no external binary required.

Features
--------
* Load and preview any DBC file — messages and their signals shown in a tree.
* Select / deselect individual messages (or entire groups) to control which
  pack/unpack functions get generated.
* Auto-group similar messages by common name prefix + numeric suffix
  (e.g. 40 radar-object messages become one collapsible group).
* Live search / filter across message names.
* cantools generation options (floating-point, bit-fields, float vs double,
  rounding, per-node filtering) exposed as toggle switches.
* Output filter: optionally strip LENGTH / IS_EXTENDED / cycle-time #defines,
  frame/signal name macros, and validate (is_in_range) functions from the
  generated files.
* Generation runs in a background thread; a progress bar and coloured log
  pane keep you informed.

Requirements
------------
    pip install ttkbootstrap>=1.10.0 cantools

Usage
-----
    python3 gui.py
"""

import json
import re
import sys
import threading
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

try:
    import ttkbootstrap as ttk
    from ttkbootstrap.constants import *
except ImportError:
    print(
        "ERROR: ttkbootstrap is required.\n"
        "Install it with:  pip install ttkbootstrap>=1.10.0",
        file=sys.stderr,
    )
    sys.exit(1)

try:
    import cantools
    import cantools.database
    from cantools.database.can.c_source import (
        generate as _ct_generate,
        camel_to_snake_case as _ct_snake,
    )
except ImportError:
    print(
        "ERROR: cantools is required.\n"
        "Install it with:  pip install cantools",
        file=sys.stderr,
    )
    sys.exit(1)

import tkinter as tk
from tkinter import filedialog, messagebox

# ── Constants ──────────────────────────────────────────────────────────────────

CHECKBOX_ON = "☑"
CHECKBOX_OFF = "☐"
CHECKBOX_PARTIAL = "⊟"

FID_ON  = "⬤"   # frame-ID prefix enabled
FID_OFF = "○"   # frame-ID prefix disabled

GROUP_MIN_SIZE = 2       # Minimum messages required to form an auto-group
APP_VERSION = "1.0"

CONFIG_PATH = Path.home() / ".c_coderdbc_gui.json"


# ── Generation helpers ─────────────────────────────────────────────────────────

def _strip_section(text: str, section_comment: str) -> str:
    """Remove a ``/* {section_comment} */`` block and its content.

    Each section in the cantools-generated header consists of a comment line
    followed by one or more ``#define`` lines and a blank-line separator.
    The entire block (comment + defines + trailing blank line) is replaced
    with a single blank line so surrounding sections remain readable.

    The pattern handles sections that contain internal blank lines, such as
    the ``Signal choices.`` section when a message has multiple signals with
    choices (cantools emits a blank line between each signal's group of choice
    defines).  Matching stops at the opening ``/* `` of the next section so
    no unrelated content is consumed.
    """
    # Stop matching when the next line begins another /* comment */ section.
    pattern = rf'/\* {re.escape(section_comment)} \*/\n(?:(?!/\* ).*\n|\n)*'
    return re.sub(pattern, '\n', text)


def _strip_validate_funcs(text: str) -> str:
    """Remove ``_is_in_range`` / ``_is_in_phys_range`` from header or source.

    **Header** pattern — a doxygen block immediately before a ``bool``
    declaration (as generated by cantools ``SIGNAL_DECLARATION_IS_IN_RANGE_FMT``
    and ``SIGNAL_DECLARATION_IS_IN_PHYS_RANGE_FMT``)::

        /**
         * Check that given signal is in allowed range.
         * ...
         */
        bool db_msg_sig_is_in_range(int16_t value);

    **Source** pattern — a bare function definition whose body contains at most
    one level of nested braces (the cantools-generated bodies are always a
    single ``return (expr);`` statement with no nested ``{}``)::

        bool db_msg_sig_is_in_range(int16_t value)
        {
            return ((value >= 0) && (value <= 100));
        }
    """
    # Header: doxygen comment block + bool declaration
    text = re.sub(
        r'/\*\*\n(?:\s*\*[^\n]*\n)*\s*\*/\nbool [^\n]+_is_in(?:_phys)?_range[^\n]+;\n',
        '',
        text,
    )
    # Source: function definition; allow one level of nested braces in the body
    # (cantools generates simple single-expression bodies, but be defensive)
    text = re.sub(
        r'bool [^\n]+_is_in(?:_phys)?_range[^\n]+\n\{(?:[^{}]|\{[^{}]*\})*\}\n',
        '',
        text,
    )
    return text


def _common_suffix_ci(names: List[str]) -> str:
    """Return the longest common suffix shared by all *names* (case-insensitive)."""
    if not names:
        return ""
    lower = [n.lower() for n in names]
    ref = lower[0]
    for length in range(len(ref), 0, -1):
        candidate = ref[-length:]
        if all(n.endswith(candidate) for n in lower):
            return candidate
    return ""


def _strip_redundant_signal_suffixes(
    header: str,
    source: str,
    groups: Dict[str, List],
    selected_names: Set[str],
) -> Tuple[str, str]:
    """Remove redundant common suffix from signal identifiers in grouped-message output.

    When every signal in a representative grouped message shares the same
    trailing suffix (e.g. ``_Obj_00`` in a group of ``ARS_Obj_00`` …
    ``ARS_Obj_63``), cantools emits function names like
    ``ars_obj_00_dist_x_obj_00_encode``.  This post-pass strips the repeated
    suffix so the result is ``ars_obj_00_dist_x_encode``.

    The replacement targets only all-lowercase (function/variable/struct-member
    names) and all-uppercase (#define macro names) identifier tokens; mixed-case
    string literals and doxygen comments are left untouched.
    """
    for msgs in groups.values():
        if len(msgs) < 2:
            continue
        rep = next((m for m in msgs if m.name in selected_names), None)
        if rep is None or not rep.signals:
            continue

        # Build the C-identifier form of each signal name using the same
        # conversion cantools uses: camel_to_snake_case for lowercase identifiers
        # (function names, struct members) and camel_to_snake_case + upper for
        # #define macro names.
        sig_ids_lower = [_ct_snake(s.name) for s in rep.signals]
        sig_ids_upper = [_ct_snake(s.name).upper() for s in rep.signals]

        suffix_lower = _common_suffix_ci(sig_ids_lower)
        if not suffix_lower or not suffix_lower.startswith("_") or len(suffix_lower) < 2:
            continue
        suffix_upper = _common_suffix_ci(sig_ids_upper)
        if not suffix_upper or not suffix_upper.startswith("_"):
            continue

        # Verify stripping would not create duplicate or empty identifiers.
        strip_lo = len(suffix_lower)
        strip_up = len(suffix_upper)
        new_lower = [n[:-strip_lo] for n in sig_ids_lower]
        new_upper = [n[:-strip_up] for n in sig_ids_upper]
        if (not all(new_lower)
                or len(set(new_lower)) != len(new_lower)
                or not all(new_upper)):
            continue

        # Sort longest-first so a longer name is replaced before any shorter
        # name that shares a suffix with it, avoiding partial-match surprises.
        quads = sorted(
            zip(sig_ids_lower, new_lower, sig_ids_upper, new_upper),
            key=lambda t: len(t[0]),
            reverse=True,
        )
        for old_lo, new_lo, old_up, new_up in quads:
            header = header.replace(old_lo, new_lo).replace(old_up, new_up)
            source = source.replace(old_lo, new_lo).replace(old_up, new_up)

    return header, source


def _strip_grouped_message_name_prefix(
    header: str,
    source: str,
    groups: Dict[str, List],
    selected_names: Set[str],
) -> Tuple[str, str]:
    """Strip the snake_case message-name segment from grouped-message identifiers.

    After the identifier-prefix replacement step identifiers for a grouped
    representative message ``ARS_Obj_00`` look like::

        <pfx>_ars_obj_00_dist_x_encode       (function / struct-tag)
        <PFX>_ARS_OBJ_00_DIST_X_NAME         (#define macro)

    Since the grouping already captures the per-instance variation, the
    ``ars_obj_00`` / ``ARS_OBJ_00`` segment is redundant.  This pass removes
    it so the result uses only the sym_prefix::

        <pfx>_dist_x_encode
        <PFX>_DIST_X_NAME

    Only applied to genuine groups (2+ messages).  Mixed-case string literals
    (``"ARS_Obj_00"``) and doxygen comments are left untouched because they
    use the original capitalisation which neither pattern matches.
    """
    for msgs in groups.values():
        if len(msgs) < 2:
            continue
        rep = next((m for m in msgs if m.name in selected_names), None)
        if rep is None:
            continue

        msg_lower = _ct_snake(rep.name)   # e.g. "ars_obj_00"
        msg_upper = msg_lower.upper()     # e.g. "ARS_OBJ_00"

        # Strip "ars_obj_00_" and "ARS_OBJ_00_" from all identifiers.
        # String literals always use the original mixed case ("ARS_Obj_00")
        # so simple str.replace is both sufficient and safe here.
        header = header.replace(msg_lower + "_", "").replace(msg_upper + "_", "")
        source = source.replace(msg_lower + "_", "").replace(msg_upper + "_", "")

    return header, source


def _strip_message_name_prefix(
    header: str,
    source: str,
    groups: Dict[str, List],
    selected_names: Set[str],
    frame_id_prefix_items: Set[str],
) -> Tuple[str, str]:
    """Strip the message/group name prefix from all generated identifiers.

    This is the per-message generalisation of
    :func:`_strip_grouped_message_name_prefix`.  While that helper only acts on
    genuine multi-message groups, this function applies to **every** selected
    message or group — including single-message entries.

    After the earlier prefix-normalisation steps, each group or single message
    contributes identifiers of the form::

        <group_or_msg_name>_<signal_name>_encode
        <GROUP_OR_MSG_NAME>_<SIGNAL_NAME>_ENCODE_MAX

    This pass removes the leading ``<group_or_msg_name>_`` segment so only the
    signal-derived part remains::

        <signal_name>_encode
        <SIGNAL_NAME>_ENCODE_MAX

    Entries that already had the frame-ID prefix applied (i.e. their group key
    is in *frame_id_prefix_items*) are skipped — their prefix is already the
    hex frame ID, not the message name.

    Mixed-case string literals are unaffected because they use the original
    capitalisation, which does not match the all-lower / all-upper patterns.
    """
    for group_key, msgs in groups.items():
        if group_key in frame_id_prefix_items:
            continue  # fid prefix was already applied; leave those identifiers alone
        rep = next((m for m in msgs if m.name in selected_names), None)
        if rep is None:
            continue

        name_lower = _ct_snake(group_key)
        name_upper = name_lower.upper()

        header = header.replace(name_lower + "_", "").replace(name_upper + "_", "")
        source = source.replace(name_lower + "_", "").replace(name_upper + "_", "")

    return header, source


def _inject_group_frame_ids(
    header: str,
    groups: Dict[str, List],
    selected_names: Set[str],
    sym_prefix: str,
) -> str:
    """Inject per-message frame-ID macros for every selected message in a group.

    When code is generated for a group, cantools only emits macros for the
    representative (first selected) member.  This function appends the missing
    macros for the remaining selected members so every message ID and its
    companion constants are present in the header.
    """
    effective_prefix = (sym_prefix.upper() + "_") if sym_prefix else ""

    # Collect non-representative selected messages across all multi-message groups.
    extra_msgs = []
    for msgs in groups.values():
        if len(msgs) < 2:
            continue
        sel_msgs = [m for m in msgs if m.name in selected_names]
        if len(sel_msgs) < 2:
            continue
        extra_msgs.extend(sel_msgs[1:])  # first entry is the representative

    if not extra_msgs:
        return header

    pfx = effective_prefix

    def _append_to_section(text: str, comment: str, new_lines: List[str]) -> str:
        """Insert *new_lines* at the end of a ``/* comment */`` section."""
        if not new_lines:
            return text
        pattern = rf'(/\* {re.escape(comment)} \*/\n(?:[^\n]+\n)*)\n'
        def _repl(m: "re.Match") -> str:
            return m.group(1) + "\n".join(new_lines) + "\n\n"
        return re.sub(pattern, _repl, text, count=1)

    header = _append_to_section(
        header, "Frame ids.",
        [f"#define {pfx}{m.name.upper()}_FRAME_ID (0x{m.frame_id:x}u)" for m in extra_msgs],
    )
    header = _append_to_section(
        header, "Frame lengths in bytes.",
        [f"#define {pfx}{m.name.upper()}_LENGTH ({m.length}u)" for m in extra_msgs],
    )
    header = _append_to_section(
        header, "Extended or standard frame types.",
        [f"#define {pfx}{m.name.upper()}_IS_EXTENDED ({1 if m.is_extended_frame else 0})"
         for m in extra_msgs],
    )
    cyc_lines = [
        f"#define {pfx}{m.name.upper()}_CYCLE_TIME_MS ({int(m.cycle_time)}u)"
        for m in extra_msgs
        if getattr(m, "cycle_time", None) is not None
    ]
    header = _append_to_section(header, "Frame cycle times in milliseconds.", cyc_lines)
    header = _append_to_section(
        header, "Frame Names.",
        [f'#define {pfx}{m.name.upper()}_NAME "{m.name}"' for m in extra_msgs],
    )
    return header


def _inject_group_range_macros(
    header: str,
    groups: Dict[str, List],
    selected_names: Set[str],
) -> str:
    """Inject ``xxx_FRAME_ID_FIRST``, ``xxx_FRAME_ID_LAST``, and
    ``xxx_FRAME_ID_COUNT`` macros into the header for every genuine group.

    The macros are appended to the *Frame ids.* section so they sit right
    alongside the individual per-message ``_FRAME_ID`` macros.  Messages
    within a group are ordered by ascending frame ID.

    Example output for group key ``ARS_Obj`` (6 messages, IDs 0x400–0x405)::

        #define ARS_OBJ_FRAME_ID_FIRST (0x400u)
        #define ARS_OBJ_FRAME_ID_LAST  (0x405u)
        #define ARS_OBJ_FRAME_ID_COUNT (6u)
    """
    range_lines: List[str] = []

    for group_key, msgs in groups.items():
        if len(msgs) < 2:
            continue
        sel_msgs = [m for m in msgs if m.name in selected_names]
        if not sel_msgs:
            continue
        ids = sorted(m.frame_id for m in sel_msgs)
        group_upper = _ct_snake(group_key).upper()
        range_lines.extend([
            f"#define {group_upper}_FRAME_ID_FIRST (0x{ids[0]:x}u)",
            f"#define {group_upper}_FRAME_ID_LAST  (0x{ids[-1]:x}u)",
            f"#define {group_upper}_FRAME_ID_COUNT ({len(ids)}u)",
        ])

    if not range_lines:
        return header

    def _append_to_section(text: str, comment: str, new_lines: List[str]) -> str:
        if not new_lines:
            return text
        pattern = rf'(/\* {re.escape(comment)} \*/\n(?:[^\n]+\n)*)\n'
        def _repl(m: "re.Match") -> str:
            return m.group(1) + "\n".join(new_lines) + "\n\n"
        return re.sub(pattern, _repl, text, count=1)

    return _append_to_section(header, "Frame ids.", range_lines)


def _replace_bitshift_funcs(source: str, bitshift_header: str) -> str:
    """Replace the inline bitshift helper block with a user-supplied ``#include``.

    The generated ``.c`` file contains a block of ``static inline`` helper
    functions (``pack_left_shift_*``, ``pack_right_shift_*``,
    ``unpack_left_shift_*``, ``unpack_right_shift_*``) immediately after the
    ``#include "drvname.h"`` line.  When *bitshift_header* is non-empty, that
    entire block is removed and ``#include "<bitshift_header>"`` is inserted in
    its place.  Passing an empty string leaves the inline functions unchanged.
    """
    # Each helper matches: "static inline <type> <name>(<args>)\n{\n    return ...;\n}\n\n"
    # [^)]+ covers the (possibly multi-line) argument list; [^}]+ covers the body.
    pattern = r"(?:static inline \S+ \S+\([^)]+\)\n\{[^}]+\}\n\n)+"
    return re.sub(pattern, f'#include "{bitshift_header}"\n\n', source, count=1)


def _replace_identifier_prefix(
    header: str, source: str, drv_name: str, new_prefix: str
) -> Tuple[str, str]:
    """Replace (or strip) the cantools database-name identifier prefix.

    cantools prefixes every generated symbol with ``database_name``.  This
    function replaces that prefix with *new_prefix* in all identifiers of the
    generated header and source, then restores the include guard (which must
    stay derived from the output file name, not from the identifier prefix).

    *new_prefix* = ``""`` strips the prefix entirely so symbols become
    ``msgname_pack`` instead of ``dbname_msgname_pack``.
    """
    from_lower = re.escape(drv_name.lower()) + "_"
    from_upper = re.escape(drv_name.upper()) + "_"
    to_lower = (new_prefix.lower() + "_") if new_prefix else ""
    to_upper = (new_prefix.upper() + "_") if new_prefix else ""

    # Negative lookbehind: only replace at the start of an identifier token.
    pat_lower = r"(?<![a-zA-Z0-9_])" + from_lower
    pat_upper = r"(?<![a-zA-Z0-9_])" + from_upper

    for pat, repl in [(pat_upper, to_upper), (pat_lower, to_lower)]:
        header = re.sub(pat, repl, header)
        source = re.sub(pat, repl, source)

    # Restore the include guard.  cantools built it as
    # f'{database_name.upper()}_H'; after our replacement it is
    # f'{to_upper}H' (e.g. '' + 'H' = 'H' when prefix is blank).
    # We always want the guard to reflect the output file name (drv_name.h).
    orig_guard = drv_name.upper() + "_H"
    new_guard = to_upper + "H"
    if new_guard != orig_guard:
        header = header.replace(f"#ifndef {new_guard}\n", f"#ifndef {orig_guard}\n", 1)
        header = header.replace(f"#define {new_guard}\n", f"#define {orig_guard}\n", 1)
        header = header.replace(f"/* {new_guard} */",     f"/* {orig_guard} */")

    return header, source


def _rename_grouped_message_prefix(
    header: str,
    source: str,
    groups: Dict[str, List],
    selected_names: Set[str],
) -> Tuple[str, str]:
    """Rename the representative message's identifier prefix to the group key.

    After the drv-name strip, grouped messages still carry the representative
    message's snake-case name as a prefix::

        ars_obj_00_dist_x_encode       (group key: ARS_Obj, rep: ARS_Obj_00)

    This pass replaces the representative-message segment with the group key::

        ars_obj_dist_x_encode

    Only applied to genuine groups (2+ messages) where the group key's
    snake-case name differs from the representative's.  String literals
    like ``"ARS_Obj_00"`` are unaffected because they use the original
    mixed-case spelling, which does not match the all-lower / all-upper
    identifier patterns.
    """
    for group_key, msgs in groups.items():
        if len(msgs) < 2:
            continue
        rep = next((m for m in msgs if m.name in selected_names), None)
        if rep is None:
            continue

        msg_lower = _ct_snake(rep.name)     # e.g. "ars_obj_00"
        group_lower = _ct_snake(group_key)  # e.g. "ars_obj"

        if msg_lower == group_lower:
            continue  # representative name already matches group key

        msg_upper = msg_lower.upper()
        group_upper = group_lower.upper()

        # Replace identifier segments that carry the representative's name.
        # The trailing "_" avoids partial word matches.
        header = header.replace(msg_lower + "_", group_lower + "_")
        header = header.replace(msg_upper + "_", group_upper + "_")
        source = source.replace(msg_lower + "_", group_lower + "_")
        source = source.replace(msg_upper + "_", group_upper + "_")

    return header, source


def _apply_frame_id_prefix(
    header: str,
    source: str,
    groups: Dict[str, List],
    selected_names: Set[str],
    frame_id_prefix_items: Set[str],
) -> Tuple[str, str]:
    """Replace the group/message name prefix with a hex frame-ID prefix.

    For groups/messages whose key is in *frame_id_prefix_items*, replaces the
    group-key-derived identifier prefix with ``x{frame_id:x}_``.  For example,
    if group key ``ARS_Obj`` has representative frame ID ``0x400``, every
    identifier like ``ars_obj_dist_x_encode`` becomes ``x400_dist_x_encode``.

    This is useful when signal names don't share the frame-name prefix and the
    auto-grouped name would produce misleading identifiers.
    """
    for group_key, msgs in groups.items():
        if group_key not in frame_id_prefix_items:
            continue
        rep = next((m for m in msgs if m.name in selected_names), None)
        if rep is None:
            continue

        group_lower = _ct_snake(group_key)
        group_upper = group_lower.upper()
        fid_lower = f"x{rep.frame_id:x}"
        fid_upper = fid_lower.upper()

        header = header.replace(group_lower + "_", fid_lower + "_")
        header = header.replace(group_upper + "_", fid_upper + "_")
        source = source.replace(group_lower + "_", fid_lower + "_")
        source = source.replace(group_upper + "_", fid_upper + "_")

    return header, source


# ── Auto-grouping ──────────────────────────────────────────────────────────────

def detect_groups(
    messages: List["cantools.database.Message"],
    min_size: int = GROUP_MIN_SIZE,
) -> Dict[str, List["cantools.database.Message"]]:
    """
    Detect groups of similarly-named messages.

    Messages whose names end with a numeric suffix (``<prefix>_?<digits>``,
    e.g. ``ARS_Obj_00`` … ``ARS_Obj_105``) or a single-character alphabetic
    suffix after an underscore (``<prefix>_<letter>``, e.g. ``Name_k`` …
    ``Name_n``) are placed in a group named ``<prefix>``.  Groups with fewer
    than *min_size* members are kept as individual entries.

    Returns a plain dict: ``group_name → [Message, …]``.
    """
    _NUM_SUFFIX   = re.compile(r"^(.*?)_?(\d+)$")
    _ALPHA_SUFFIX = re.compile(r"^(.+?)_([a-zA-Z])$")
    bucket: Dict[str, List] = defaultdict(list)

    for msg in messages:
        m = _NUM_SUFFIX.match(msg.name)
        if m:
            prefix = m.group(1).rstrip("_") or msg.name
            bucket[prefix].append(msg)
        else:
            m = _ALPHA_SUFFIX.match(msg.name)
            if m:
                bucket[m.group(1)].append(msg)
            else:
                bucket[msg.name].append(msg)

    groups: Dict[str, List] = {}
    for prefix, msgs in bucket.items():
        if len(msgs) >= min_size:
            groups[prefix] = sorted(msgs, key=lambda x: x.frame_id)
        else:
            for msg in msgs:
                groups[msg.name] = [msg]

    return groups


# ── Main Application ──────────────────────────────────────────────────────────

class CoderDbcGui(ttk.Window):
    """
    Main application window for the C-CoderDBC GUI.

    Layout
    ------
    Left pane  — DBC tree (messages → signals) with checkbox selection,
                 search bar, and group controls.
    Right pane — Tabbed panel: Settings tab (paths, options, generate button)
                 and Output Log tab (coloured text console).
    """

    APP_TITLE = f"C-CoderDBC GUI  v{APP_VERSION}"

    def __init__(self) -> None:
        super().__init__(
            title=self.APP_TITLE,
            themename="darkly",
            size=(1400, 1020),
            minsize=(1060, 800),
        )

        # ── Application variables ───────────────────────────────────────────
        self._dbc_path = tk.StringVar()
        self._out_path = tk.StringVar()
        self._drv_name = tk.StringVar()
        self._sym_prefix = tk.StringVar()   # identifier prefix (blank = strip entirely)
        self._search_var = tk.StringVar()
        self._summary_var = tk.StringVar(value="No DBC file loaded")
        self._sel_summary = tk.StringVar(value="0 messages selected")

        # ── cantools generation options ─────────────────────────────────────
        self._opt_fp        = tk.BooleanVar(value=True)   # floating_point_numbers
        self._opt_bitfields = tk.BooleanVar(value=False)  # bit_fields
        self._opt_use_float = tk.BooleanVar(value=False)  # use_float
        self._opt_use_round = tk.BooleanVar(value=False)  # use_round
        self._node_name     = tk.StringVar(value="")      # node_name

        # ── Output filter toggles ────────────────────────────────────────────
        self._opt_skip_length      = tk.BooleanVar(value=False)
        self._opt_skip_extended    = tk.BooleanVar(value=False)
        self._opt_skip_cycle_time  = tk.BooleanVar(value=False)
        self._opt_skip_frame_names = tk.BooleanVar(value=False)
        self._opt_skip_sig_names   = tk.BooleanVar(value=False)
        self._opt_skip_validate    = tk.BooleanVar(value=False)
        self._opt_skip_choices     = tk.BooleanVar(value=False)

        # ── Group / bitshift options ─────────────────────────────────────────
        self._opt_expand_group_ids    = tk.BooleanVar(value=False)
        self._opt_strip_sig_suffix    = tk.BooleanVar(value=True)
        self._opt_strip_msg_name_prefix = tk.BooleanVar(value=False)
        self._bitshift_header         = tk.StringVar(value="")

        # Per-group/message frame-ID prefix: set of group keys whose identifiers
        # should be prefixed with the hex frame-ID (e.g. x400_) instead of the
        # group name.  Toggled via right-click context menu on tree rows.
        self._frame_id_prefix_items: Set[str] = set()

        # Ordered list used by the master toggle to iterate all filter vars.
        self._filter_vars: List[tk.BooleanVar] = [
            self._opt_skip_length,
            self._opt_skip_extended,
            self._opt_skip_cycle_time,
            self._opt_skip_frame_names,
            self._opt_skip_sig_names,
            self._opt_skip_validate,
            self._opt_skip_choices,
            self._opt_expand_group_ids,
            self._opt_strip_sig_suffix,
        ]
        # Master toggle var: True = all on, False = all off (no tri-state var needed).
        self._opt_filter_master = tk.BooleanVar(value=False)
        # Keep master in sync whenever any individual filter changes.
        for _v in self._filter_vars:
            _v.trace_add("write", lambda *_: self._sync_filter_master())

        # ── Internal state ──────────────────────────────────────────────────
        self._db: Optional[cantools.database.Database] = None
        self._messages: List[cantools.database.can.Message] = []
        self._groups: Dict[str, List[cantools.database.can.Message]] = {}
        # Maps internal group key → user-chosen display name (survives repopulates)
        self._group_aliases: Dict[str, str] = {}
        # Selected message names (cantools message names are unique within a db)
        self._selected: Set[str] = set()
        # Maps tree-item IID → ("group", group_name) | ("msg", cantools Message)
        self._tree_items: Dict[str, Tuple[str, object]] = {}
        # Active inline-rename Entry widget (None when no rename is in progress)
        self._rename_entry: Optional[tk.Entry] = None
        self._rename_group_key: Optional[str] = None

        # ── Build UI ────────────────────────────────────────────────────────
        self._build_ui()

        # ── Restore saved settings, then bind close handler ─────────────────
        self._load_config()
        self.protocol("WM_DELETE_WINDOW", self._on_close)

        # Auto-reload last DBC file if it still exists on disk
        last_path = self._dbc_path.get()
        if last_path and Path(last_path).is_file():
            self.after(100, lambda: self._load_dbc(last_path))

    # ── UI Construction ──────────────────────────────────────────────────────

    def _build_ui(self) -> None:
        # Title bar
        hdr = ttk.Frame(self, padding=(10, 6))
        hdr.pack(fill=X)
        ttk.Label(
            hdr, text="C-CoderDBC", font=("", 18, "bold"), bootstyle="primary"
        ).pack(side=LEFT)
        ttk.Label(
            hdr, text="  DBC Preview & C Code Generator", bootstyle="secondary"
        ).pack(side=LEFT)

        ttk.Separator(self, orient=HORIZONTAL).pack(fill=X)

        # Main split: left = tree, right = settings+log
        paned = ttk.Panedwindow(self, orient=HORIZONTAL)
        paned.pack(fill=BOTH, expand=True, padx=6, pady=6)

        left = ttk.Frame(paned, padding=4)
        right = ttk.Frame(paned, padding=4)
        paned.add(left, weight=13)
        paned.add(right, weight=7)

        self._build_tree_panel(left)
        self._build_right_panel(right)

    # ── Left panel — DBC tree ────────────────────────────────────────────────

    def _build_tree_panel(self, parent: ttk.Frame) -> None:
        # Header
        hdr = ttk.Frame(parent)
        hdr.pack(fill=X, pady=(0, 4))
        ttk.Label(hdr, text="DBC Preview", font=("", 12, "bold")).pack(side=LEFT)
        ttk.Button(
            hdr, text="📂  Load DBC…", command=self._browse_dbc, bootstyle="primary"
        ).pack(side=RIGHT)

        # File path (read-only)
        ttk.Entry(
            parent, textvariable=self._dbc_path, state="readonly", bootstyle="secondary"
        ).pack(fill=X, pady=(0, 4))

        # Toolbar
        toolbar = ttk.Frame(parent)
        toolbar.pack(fill=X, pady=4)

        ttk.Label(toolbar, text="🔍").pack(side=LEFT)
        ttk.Entry(toolbar, textvariable=self._search_var, width=20).pack(
            side=LEFT, padx=(2, 8)
        )
        self._search_var.trace_add("write", lambda *_: self._apply_filter())

        ttk.Button(
            toolbar, text="Auto-Group", command=self._auto_group, bootstyle="info-outline"
        ).pack(side=LEFT, padx=2)
        ttk.Button(
            toolbar, text="Ungroup", command=self._ungroup, bootstyle="secondary-outline"
        ).pack(side=LEFT, padx=2)

        ttk.Separator(toolbar, orient=VERTICAL).pack(side=LEFT, fill=Y, padx=8)

        ttk.Button(
            toolbar, text="✓ All", command=self._select_all, bootstyle="success-outline"
        ).pack(side=LEFT, padx=2)
        ttk.Button(
            toolbar, text="✗ None", command=self._deselect_all, bootstyle="danger-outline"
        ).pack(side=LEFT, padx=2)

        # Summary label
        ttk.Label(
            parent, textvariable=self._summary_var, bootstyle="secondary"
        ).pack(anchor=W, pady=(2, 0))

        # Tree container
        tree_container = ttk.Frame(parent)
        tree_container.pack(fill=BOTH, expand=True, pady=(4, 0))

        # Increase Treeview row font from the default (~9 pt) to 11 pt so
        # message and signal names are more legible.
        self.style.configure("Treeview", font=("", 11))
        self.style.configure("Treeview.Heading", font=("", 10, "bold"))

        cols = ("sel", "fid", "id", "name", "dlc", "signals", "transmitter")
        self._tree = ttk.Treeview(
            tree_container,
            columns=cols,
            show="headings",
            selectmode="browse",
            bootstyle="primary",
        )
        self._tree.heading(
            "sel", text=CHECKBOX_OFF,
            anchor=W,
            command=self._toggle_all_heading,
        )
        self._tree.heading("fid", text="fid", anchor=CENTER)
        self._tree.heading("id", text="ID (hex)")
        self._tree.heading("name", text="Name")
        self._tree.heading("dlc", text="DLC")
        self._tree.heading("signals", text="Signals")
        self._tree.heading("transmitter", text="Transmitter")

        self._tree.column("sel",         width=32,  minwidth=32,  anchor=W,      stretch=False)
        self._tree.column("fid",         width=34,  minwidth=34,  anchor=CENTER, stretch=False)
        self._tree.column("id",          width=90,  minwidth=70,  anchor=W,      stretch=False)
        self._tree.column("name",        width=240, minwidth=140)
        self._tree.column("dlc",         width=50,  minwidth=40,  anchor=CENTER)
        self._tree.column("signals",     width=60,  minwidth=40,  anchor=CENTER)
        self._tree.column("transmitter", width=110, minwidth=70,  anchor=CENTER)

        vsb = ttk.Scrollbar(tree_container, orient=VERTICAL, command=self._tree.yview)
        hsb = ttk.Scrollbar(tree_container, orient=HORIZONTAL, command=self._tree.xview)
        self._tree.configure(yscrollcommand=vsb.set, xscrollcommand=hsb.set)

        self._tree.grid(row=0, column=0, sticky="nsew")
        vsb.grid(row=0, column=1, sticky="ns")
        hsb.grid(row=1, column=0, sticky="ew")
        tree_container.rowconfigure(0, weight=1)
        tree_container.columnconfigure(0, weight=1)

        self._tree.bind("<ButtonRelease-1>", self._on_tree_click)
        self._tree.bind("<Double-Button-1>", self._on_tree_double_click)

    # ── Right panel — Settings + Log ─────────────────────────────────────────

    def _build_right_panel(self, parent: ttk.Frame) -> None:
        nb = ttk.Notebook(parent, bootstyle="primary")
        nb.pack(fill=BOTH, expand=True)

        settings_frame = ttk.Frame(nb, padding=10)
        nb.add(settings_frame, text=" ⚙  Settings ")
        self._build_settings_tab(settings_frame)

        log_frame = ttk.Frame(nb, padding=6)
        nb.add(log_frame, text=" 📋  Output Log ")
        self._build_log_tab(log_frame)

    def _build_settings_tab(self, parent: ttk.Frame) -> None:
        ttk.Label(
            parent, text="Code Generation Settings", font=("", 11, "bold")
        ).pack(anchor=W, pady=(0, 8))

        # Output directory
        ttk.Label(parent, text="Output directory").pack(anchor=W)
        out_row = ttk.Frame(parent)
        out_row.pack(fill=X, pady=(2, 8))
        ttk.Entry(out_row, textvariable=self._out_path).pack(
            side=LEFT, fill=X, expand=True
        )
        ttk.Button(out_row, text="…", width=3, command=self._browse_out_dir).pack(
            side=LEFT, padx=(4, 0)
        )

        # Driver name
        ttk.Label(parent, text="Driver name").pack(anchor=W)
        ttk.Entry(parent, textvariable=self._drv_name).pack(fill=X, pady=(2, 6))

        # Identifier prefix
        ttk.Label(
            parent, text="Identifier prefix  (blank = no prefix in symbol names)"
        ).pack(anchor=W)
        ttk.Entry(parent, textvariable=self._sym_prefix).pack(fill=X, pady=(2, 8))

        ttk.Separator(parent).pack(fill=X, pady=8)

        # ── cantools options ─────────────────────────────────────────────────
        ttk.Label(parent, text="cantools Options", font=("", 10, "bold")).pack(
            anchor=W, pady=(0, 4)
        )

        gen_opts = [
            (self._opt_fp,        "Floating-point encode/decode"),
            (self._opt_bitfields, "Bit fields in structs"),
            (self._opt_use_float, "Use float (not double)"),
            (self._opt_use_round, "Round encoded values (not truncate)"),
        ]
        for var, label in gen_opts:
            ttk.Checkbutton(
                parent, text=label, variable=var, bootstyle="primary-round-toggle"
            ).pack(anchor=W, pady=2)

        # Node name
        ttk.Label(parent, text="Node name (optional)").pack(anchor=W, pady=(6, 0))
        ttk.Entry(parent, textvariable=self._node_name).pack(fill=X, pady=(2, 0))

        ttk.Separator(parent).pack(fill=X, pady=8)

        # ── Output filter ────────────────────────────────────────────────────
        filter_hdr = ttk.Frame(parent)
        filter_hdr.pack(fill=X, pady=(0, 4))
        ttk.Checkbutton(
            filter_hdr,
            text="",
            variable=self._opt_filter_master,
            command=self._on_filter_master_toggle,
            bootstyle="warning-round-toggle",
        ).pack(side=LEFT)
        ttk.Label(filter_hdr, text="Output filters", font=("", 10, "bold")).pack(side=LEFT, padx=(6, 0))

        filter_opts = [
            (self._opt_skip_length,      "Skip LENGTH #defines"),
            (self._opt_skip_extended,    "Skip IS_EXTENDED #defines"),
            (self._opt_skip_cycle_time,  "Skip cycle-time #defines"),
            (self._opt_skip_frame_names, "Skip frame-name macros"),
            (self._opt_skip_sig_names,   "Skip signal-name macros"),
            (self._opt_skip_validate,    "Skip validate functions (is_in_range)"),
            (self._opt_skip_choices,     "Skip signal choices macros (_CHOICE)"),
            (self._opt_expand_group_ids, "Expand groups: emit frame ID macros for all grouped messages"),
            (self._opt_strip_sig_suffix, "Strip redundant signal suffix in groups"),
            (self._opt_strip_msg_name_prefix, "Strip message name from signal symbols  (e.g. msg_sig_encode → sig_encode)"),
        ]
        for var, label in filter_opts:
            ttk.Checkbutton(
                parent, text=label, variable=var, bootstyle="warning-round-toggle"
            ).pack(anchor=W, pady=2)

        ttk.Separator(parent).pack(fill=X, pady=8)

        # ── Bitshift helpers ─────────────────────────────────────────────────
        ttk.Label(parent, text="Bitshift Helpers", font=("", 10, "bold")).pack(
            anchor=W, pady=(0, 4)
        )
        ttk.Label(
            parent,
            text="Bitshift header file  (blank = keep inline functions in .c)",
            bootstyle="secondary",
        ).pack(anchor=W)
        ttk.Entry(parent, textvariable=self._bitshift_header).pack(fill=X, pady=(2, 0))

        ttk.Separator(parent).pack(fill=X, pady=8)

        ttk.Label(parent, textvariable=self._sel_summary, bootstyle="info").pack(
            anchor=W
        )

        self._gen_btn = ttk.Button(
            parent,
            text="⚡  Generate C Code",
            command=self._generate,
            bootstyle="success",
        )
        self._gen_btn.pack(fill=X, pady=(8, 4))

        self._progress = ttk.Progressbar(
            parent, bootstyle="secondary", mode="determinate"
        )
        self._progress.pack(fill=X, pady=(0, 4))
        # Starts at 0 (greyed/empty); becomes animated during generation.

    def _build_log_tab(self, parent: ttk.Frame) -> None:
        text_frame = ttk.Frame(parent)
        text_frame.pack(fill=BOTH, expand=True)

        self._log_text = tk.Text(
            text_frame,
            state="disabled",
            wrap="word",
            font=("Courier", 9),
            bg="#1e1e1e",
            fg="#d4d4d4",
            insertbackground="white",
            relief="flat",
        )
        vsb = ttk.Scrollbar(text_frame, orient=VERTICAL, command=self._log_text.yview)
        self._log_text.configure(yscrollcommand=vsb.set)
        self._log_text.grid(row=0, column=0, sticky="nsew")
        vsb.grid(row=0, column=1, sticky="ns")
        text_frame.rowconfigure(0, weight=1)
        text_frame.columnconfigure(0, weight=1)

        # Colour tags for log levels
        self._log_text.tag_config("warning", foreground="#f0ad4e")
        self._log_text.tag_config("success", foreground="#5cb85c")
        self._log_text.tag_config("danger",  foreground="#d9534f")
        self._log_text.tag_config("info",    foreground="#5bc0de")

        ttk.Button(
            parent, text="Clear Log", command=self._clear_log, bootstyle="secondary-outline"
        ).pack(anchor=E, pady=4)

    # ── Output filter master toggle ───────────────────────────────────────────

    def _on_filter_master_toggle(self) -> None:
        """Set all individual filter vars to match the master toggle."""
        state = self._opt_filter_master.get()
        for v in self._filter_vars:
            v.set(state)

    def _sync_filter_master(self) -> None:
        """Keep the master toggle in sync with the individual filter states."""
        all_on = all(v.get() for v in self._filter_vars)
        # Update without re-triggering traces that call back here.
        self._opt_filter_master.set(all_on)

    # ── DBC loading ──────────────────────────────────────────────────────────

    def _browse_dbc(self) -> None:
        saved = self._dbc_path.get()
        if saved and Path(saved).parent.is_dir():
            initial = str(Path(saved).parent)
        else:
            docs = Path.home() / "Documents"
            initial = str(docs) if docs.is_dir() else str(Path.home())
        path = filedialog.askopenfilename(
            title="Select DBC file",
            initialdir=initial,
            filetypes=[("DBC files", "*.dbc"), ("All files", "*.*")],
        )
        if path:
            self._dbc_path.set(path)
            self._load_dbc(path)

    def _load_dbc(self, path: str) -> None:
        self._log(f"Loading: {path}", tag="info")
        try:
            self._db = cantools.database.load_file(path)
        except Exception as exc:
            self._log(f"ERROR parsing DBC file: {exc}", tag="danger")
            return

        self._messages = sorted(self._db.messages, key=lambda m: m.frame_id)
        self._selected = {m.name for m in self._messages}

        # Start with a flat (one group per message) layout
        self._groups = {msg.name: [msg] for msg in self._messages}
        self._group_aliases.clear()
        self._frame_id_prefix_items.clear()
        self._populate_tree()
        self._update_summary()
        self._log(f"Loaded {len(self._messages)} message(s).", tag="success")

        # Auto-fill driver name and output dir from the filename
        stem = Path(path).stem
        if not self._drv_name.get():
            self._drv_name.set(stem)
        if not self._out_path.get():
            self._out_path.set(str(Path(path).parent / "gencode"))

    # ── Tree population ───────────────────────────────────────────────────────

    def _populate_tree(self) -> None:
        """Rebuild the entire Treeview from *self._groups*, respecting the search filter."""
        self._cancel_group_rename()
        self._tree.delete(*self._tree.get_children())
        self._tree_items.clear()

        filter_text = self._search_var.get().lower()

        for group_name, msgs in sorted(
            self._groups.items(), key=lambda kv: min(m.frame_id for m in kv[1])
        ):
            visible = [
                m for m in msgs
                if not filter_text or filter_text in m.name.lower()
            ]
            if not visible:
                continue

            is_group = len(msgs) > 1

            if is_group:
                all_sel = all(m.name in self._selected for m in visible)
                any_sel = any(m.name in self._selected for m in visible)
                chk = (
                    CHECKBOX_ON if all_sel
                    else CHECKBOX_PARTIAL if any_sel
                    else CHECKBOX_OFF
                )
                total_sigs = sum(len(m.signals) for m in visible)
                g_iid = f"group::{group_name}"
                fid_val = FID_ON if group_name in self._frame_id_prefix_items else FID_OFF
                self._tree.insert(
                    "", END, iid=g_iid,
                    values=(chk, fid_val, f"0x{min(m.frame_id for m in visible):03X}+",
                            self._group_name_cell_text(group_name, "▶", visible),
                            "", total_sigs, "✎ dbl-click to rename"),
                    open=False,
                    tags=("group",),
                )
                self._tree_items[g_iid] = ("group", group_name)
                for msg in visible:
                    self._insert_message(g_iid, msg)
            else:
                self._insert_message("", msgs[0])

        self._tree.tag_configure("group",  font=("", 11, "bold"))
        self._tree.tag_configure("signal", foreground="#888888")
        self._refresh_heading()

    def _insert_message(self, parent_iid: str, msg: "cantools.database.can.Message") -> None:
        selected = msg.name in self._selected
        chk = CHECKBOX_ON if selected else CHECKBOX_OFF
        m_iid = f"msg::{msg.frame_id}"
        sender = msg.senders[0] if msg.senders else ""
        has_sigs = bool(msg.signals)
        expand_indicator = "▶  " if has_sigs else "   "
        # fid column: only shown for top-level (non-grouped) message rows
        group_key = next(
            (k for k, v in self._groups.items() if any(m.name == msg.name for m in v)),
            msg.name,
        )
        fid_val = FID_ON if group_key in self._frame_id_prefix_items else FID_OFF
        # fid toggle is irrelevant for messages inside a group (group key controls it)
        fid_display = fid_val if not parent_iid else ""
        self._tree.insert(
            parent_iid, END, iid=m_iid,
            values=(chk, fid_display, f"{expand_indicator}0x{msg.frame_id:03X}", msg.name,
                    msg.length, len(msg.signals), sender),
            open=False,
            tags=("msg",),
        )
        self._tree_items[m_iid] = ("msg", msg)

        for sig in msg.signals:
            s_iid = f"sig::{msg.frame_id}::{sig.name}"
            bo = "LE" if sig.byte_order == "little_endian" else "BE"
            vt = "S" if sig.is_signed else "U"
            self._tree.insert(
                m_iid, END, iid=s_iid,
                values=("", "", "", f"    {sig.name}  [{sig.start}|{sig.length}]", bo, vt, ""),
                tags=("signal",),
            )

    # ── Tree interaction ──────────────────────────────────────────────────────

    def _on_tree_click(self, event: "tk.Event[ttk.Treeview]") -> None:
        """Handle clicks in the sel, fid, and name columns."""
        if self._tree.identify_region(event.x, event.y) != "cell":
            return

        iid = self._tree.identify_row(event.y)
        if not iid or iid not in self._tree_items:
            return

        col = self._tree.identify_column(event.x)
        # col numbers: #1=sel, #2=fid, #3=id, #4=name, #5=dlc, #6=signals, #7=transmitter

        kind, data = self._tree_items[iid]

        if col == "#2":
            # fid column: toggle frame-ID prefix for this group/message
            if kind == "signal":
                return
            if kind == "group":
                self._toggle_frame_id_prefix(str(data))
            elif kind == "msg":
                msg = data  # type: ignore[assignment]
                group_key = next(
                    (k for k, v in self._groups.items() if any(m.name == msg.name for m in v)),  # type: ignore[union-attr]
                    msg.name,  # type: ignore[union-attr]
                )
                self._toggle_frame_id_prefix(group_key)
            return

        if col not in ("#1", "#4"):
            return

        if kind == "group":
            if col == "#4":
                # Name column click → expand/collapse the group
                self._toggle_group_expand(str(data))
                return
            # Sel column click → toggle selection of all messages in group
            self._toggle_group(str(data))
        elif kind == "msg":
            msg = data  # type: ignore[assignment]
            if col == "#4" and msg.signals:  # type: ignore[union-attr]
                self._toggle_msg_expand(msg)  # type: ignore[arg-type]
                return
            self._toggle_message(data)  # type: ignore[arg-type]

        self._update_summary()

    def _on_tree_double_click(self, event: "tk.Event[ttk.Treeview]") -> None:
        """Start an inline rename when the user double-clicks a group row's name cell."""
        if self._tree.identify_region(event.x, event.y) != "cell":
            return
        iid = self._tree.identify_row(event.y)
        if not iid or iid not in self._tree_items:
            return
        col = self._tree.identify_column(event.x)
        if col != "#4":
            return
        kind, data = self._tree_items[iid]
        if kind != "group":
            return
        self._start_group_rename(str(data))

    def _toggle_frame_id_prefix(self, group_key: str) -> None:
        """Enable or disable the frame-ID identifier prefix for *group_key*."""
        if group_key in self._frame_id_prefix_items:
            self._frame_id_prefix_items.discard(group_key)
        else:
            self._frame_id_prefix_items.add(group_key)
        fid_val = FID_ON if group_key in self._frame_id_prefix_items else FID_OFF
        # Refresh the fid column on the affected row.
        g_iid = f"group::{group_key}"
        if self._tree.exists(g_iid):
            self._tree.set(g_iid, "fid", fid_val)
        else:
            # Single-message top-level row
            msgs = self._groups.get(group_key, [])
            if msgs:
                m_iid = f"msg::{msgs[0].frame_id}"
                if self._tree.exists(m_iid):
                    self._tree.set(m_iid, "fid", fid_val)

    def _start_group_rename(self, group_key: str) -> None:
        """Overlay an Entry widget on the group row's name cell for inline editing."""
        self._cancel_group_rename()  # cancel any previous rename in progress

        g_iid = f"group::{group_key}"
        bbox = self._tree.bbox(g_iid, "name")
        if not bbox:
            return  # row not visible
        x, y, width, height = bbox

        current_name = self._group_aliases.get(group_key, group_key)
        var = tk.StringVar(value=current_name)
        entry = ttk.Entry(self._tree, textvariable=var, font=("", 11, "bold"))
        entry.place(x=x, y=y, width=width, height=height)
        entry.focus_set()
        entry.select_range(0, tk.END)

        self._rename_entry = entry
        self._rename_group_key = group_key

        entry.bind("<Return>", lambda _e: self._confirm_group_rename())
        entry.bind("<KP_Enter>", lambda _e: self._confirm_group_rename())
        entry.bind("<Escape>", lambda _e: self._cancel_group_rename())
        entry.bind("<FocusOut>", lambda _e: self._confirm_group_rename())

    def _confirm_group_rename(self) -> None:
        """Validate and apply the rename, then remove the entry widget."""
        entry = self._rename_entry
        group_key = self._rename_group_key
        if entry is None or group_key is None:
            return

        new_name = entry.get().strip()
        self._cancel_group_rename()  # destroy entry before any messagebox

        if not new_name:
            return  # empty name → silently cancel

        # Check uniqueness: no other group may already display the same name
        existing_names = {
            self._group_aliases.get(k, k)
            for k in self._groups
            if k != group_key
        }
        if new_name in existing_names:
            messagebox.showwarning(
                "Name Already Used",
                f'A group named "{new_name}" already exists.\nPlease choose a different name.',
                parent=self,
            )
            return

        self._group_aliases[group_key] = new_name

        # Update the treeview row text in-place (no full repopulate needed)
        g_iid = f"group::{group_key}"
        if self._tree.exists(g_iid):
            msgs = self._groups[group_key]
            is_open = bool(self._tree.item(g_iid, "open"))
            indicator = "▼" if is_open else "▶"
            self._tree.set(g_iid, "name", self._group_name_cell_text(group_key, indicator, msgs))

    def _cancel_group_rename(self) -> None:
        """Discard the inline rename and remove the Entry widget."""
        if self._rename_entry is not None:
            try:
                self._rename_entry.destroy()
            except tk.TclError:
                pass
            self._rename_entry = None
            self._rename_group_key = None

    def _group_name_cell_text(self, group_key: str, indicator: str, msgs: list) -> str:
        """Return the formatted text for a group row's name cell."""
        display_name = self._group_aliases.get(group_key, group_key)
        return f"{indicator}  {display_name}  ({len(msgs)} frames → 1 function set)"

    def _toggle_group_expand(self, group_name: str) -> None:
        """Flip the open/close state of a group row and update its ▶/▼ indicator."""
        g_iid = f"group::{group_name}"
        if not self._tree.exists(g_iid):
            return
        msgs = self._groups[group_name]
        is_open = bool(self._tree.item(g_iid, "open"))
        self._tree.item(g_iid, open=not is_open)
        indicator = "▼" if not is_open else "▶"
        self._tree.set(g_iid, "name", self._group_name_cell_text(group_name, indicator, msgs))

    def _toggle_msg_expand(self, msg: "cantools.database.can.Message") -> None:
        """Flip the open/close state of a message row and update its ▶/▼ indicator."""
        m_iid = f"msg::{msg.frame_id}"
        if not self._tree.exists(m_iid):
            return
        is_open = bool(self._tree.item(m_iid, "open"))
        self._tree.item(m_iid, open=not is_open)
        indicator = "▼  " if not is_open else "▶  "
        self._tree.set(m_iid, "id", f"{indicator}0x{msg.frame_id:03X}")

    def _toggle_message(self, msg: "cantools.database.can.Message") -> None:
        if msg.name in self._selected:
            self._selected.discard(msg.name)
        else:
            self._selected.add(msg.name)
        selected = msg.name in self._selected
        chk = CHECKBOX_ON if selected else CHECKBOX_OFF
        m_iid = f"msg::{msg.frame_id}"
        if self._tree.exists(m_iid):
            self._tree.set(m_iid, "sel", chk)
        self._refresh_parent_group(msg)
        self._refresh_heading()

    def _toggle_group(self, group_name: str) -> None:
        msgs = self._groups[group_name]
        all_sel = all(m.name in self._selected for m in msgs)
        if all_sel:
            for msg in msgs:
                self._selected.discard(msg.name)
        else:
            for msg in msgs:
                self._selected.add(msg.name)
        for msg in msgs:
            chk = CHECKBOX_ON if msg.name in self._selected else CHECKBOX_OFF
            m_iid = f"msg::{msg.frame_id}"
            if self._tree.exists(m_iid):
                self._tree.set(m_iid, "sel", chk)
        self._refresh_group_item(group_name)
        self._refresh_heading()

    def _refresh_group_item(self, group_name: str) -> None:
        g_iid = f"group::{group_name}"
        if not self._tree.exists(g_iid):
            return
        msgs = self._groups[group_name]
        all_sel = all(m.name in self._selected for m in msgs)
        any_sel = any(m.name in self._selected for m in msgs)
        chk = (
            CHECKBOX_ON if all_sel
            else CHECKBOX_PARTIAL if any_sel
            else CHECKBOX_OFF
        )
        n = len(msgs)
        min_id = min(m.frame_id for m in msgs)
        self._tree.set(g_iid, "sel", chk)

    def _refresh_parent_group(self, msg: "cantools.database.can.Message") -> None:
        for group_name, msgs in self._groups.items():
            if msg in msgs and len(msgs) > 1:
                self._refresh_group_item(group_name)
                break

    # ── Grouping ──────────────────────────────────────────────────────────────

    def _auto_group(self) -> None:
        if not self._messages:
            return
        self._groups = detect_groups(self._messages)
        self._group_aliases.clear()
        self._populate_tree()
        n_groups = sum(1 for v in self._groups.values() if len(v) > 1)
        self._log(
            f"Auto-grouping complete: {n_groups} group(s) detected.", tag="info"
        )

    def _ungroup(self) -> None:
        if not self._messages:
            return
        self._groups = {msg.name: [msg] for msg in self._messages}
        self._group_aliases.clear()
        self._populate_tree()

    # ── Selection helpers ─────────────────────────────────────────────────────

    def _select_all(self) -> None:
        self._selected = {m.name for m in self._messages}
        self._populate_tree()
        self._update_summary()

    def _deselect_all(self) -> None:
        self._selected.clear()
        self._populate_tree()
        self._update_summary()

    def _toggle_all_heading(self) -> None:
        """Toggle all messages on/off when the sel column heading checkbox is clicked."""
        if not self._messages:
            return
        all_sel = all(m.name in self._selected for m in self._messages)
        if all_sel:
            self._selected.clear()
        else:
            self._selected = {m.name for m in self._messages}
        self._populate_tree()
        self._update_summary()

    def _refresh_heading(self) -> None:
        """Update the sel column heading checkbox to reflect the current selection state."""
        if not self._messages:
            chk = CHECKBOX_OFF
        elif all(m.name in self._selected for m in self._messages):
            chk = CHECKBOX_ON
        elif any(m.name in self._selected for m in self._messages):
            chk = CHECKBOX_PARTIAL
        else:
            chk = CHECKBOX_OFF
        self._tree.heading("sel", text=chk)

    def _apply_filter(self) -> None:
        self._populate_tree()

    def _update_summary(self) -> None:
        total = len(self._messages)
        sel = sum(1 for m in self._messages if m.name in self._selected)
        func_sets = sum(
            1 for msgs in self._groups.values()
            if any(m.name in self._selected for m in msgs)
        )
        self._summary_var.set(f"{total} messages  |  {sel} selected")
        self._sel_summary.set(
            f"{sel} / {total} messages selected  →  {func_sets} function set(s) will be generated"
        )

    # ── Code generation ───────────────────────────────────────────────────────

    def _generate(self) -> None:
        if not self._messages:
            messagebox.showwarning("No DBC", "Please load a DBC file first.")
            return

        # For each group, emit only ONE representative message (the first selected
        # member).  This is the whole point of grouping: 111 radar frames with
        # identical signal layouts produce ONE pack/unpack function set, not 111.
        # Ungrouped (single-message) entries behave exactly as before.
        representatives: List["cantools.database.can.Message"] = []
        for msgs in sorted(self._groups.values(), key=lambda v: min(m.frame_id for m in v)):
            rep = next((m for m in msgs if m.name in self._selected), None)
            if rep is not None:
                representatives.append(rep)

        if not representatives:
            messagebox.showwarning(
                "Nothing Selected",
                "Select at least one message to generate code for.",
            )
            return

        out_dir = self._out_path.get().strip()
        drv_name = self._drv_name.get().strip()
        sym_prefix = self._sym_prefix.get().strip()

        if not out_dir:
            messagebox.showwarning("Missing", "Please specify an output directory.")
            return
        if not drv_name:
            messagebox.showwarning("Missing", "Please specify a driver name.")
            return

        # Check for file conflicts on the main thread, before starting the worker.
        out = Path(out_dir)
        h_name = f"{drv_name}.h"
        c_name = f"{drv_name}.c"
        conflicts = [f for f in (h_name, c_name) if (out / f).exists()]
        if conflicts:
            names = "\n  • ".join(conflicts)
            if not messagebox.askyesno(
                "Files Already Exist",
                f"The following file(s) already exist in:\n{out_dir}\n\n  • {names}\n\nOverwrite?",
                parent=self,
            ):
                return

        self._gen_btn.configure(state="disabled")
        self._progress.configure(bootstyle="success-striped", mode="indeterminate")
        self._progress.start(10)
        # Snapshot mutable state so the worker thread sees a consistent view.
        groups_snapshot = {k: list(v) for k, v in self._groups.items()}
        selected_snapshot = set(self._selected)
        frame_id_prefix_snapshot = set(self._frame_id_prefix_items)
        threading.Thread(
            target=self._run_generation,
            args=(representatives, out_dir, drv_name, sym_prefix,
                  groups_snapshot, selected_snapshot, frame_id_prefix_snapshot),
            daemon=True,
        ).start()

    def _run_generation(
        self,
        selected: List["cantools.database.can.Message"],
        out_dir: str,
        drv_name: str,
        sym_prefix: str,
        groups: Dict[str, List["cantools.database.can.Message"]],
        selected_names: Set[str],
        frame_id_prefix_items: Set[str],
    ) -> None:
        try:
            # Build a filtered in-memory database from the selected messages.
            filtered_db = cantools.database.Database(messages=selected)
            h_name = f"{drv_name}.h"
            c_name = f"{drv_name}.c"
            node = self._node_name.get().strip() or None

            self._log(
                f"Generating C code for {len(selected)} function set(s)…", tag="info"
            )

            header, source, _, _ = _ct_generate(
                filtered_db,
                drv_name,
                h_name,
                c_name,
                f"{drv_name}_fuzzer.c",
                floating_point_numbers=self._opt_fp.get(),
                bit_fields=self._opt_bitfields.get(),
                use_float=self._opt_use_float.get(),
                node_name=node,
                use_round=self._opt_use_round.get(),
            )

            # Post-process: always strip the cantools database/driver name prefix
            # so the message/frame name becomes the outermost identifier namespace.
            # e.g. ars_radar_ars_obj_00_dist_x_encode → ars_obj_00_dist_x_encode
            header, source = _replace_identifier_prefix(
                header, source, drv_name, ""
            )

            # Post-process: for grouped messages replace the representative
            # message's name segment with the group key so identifiers use the
            # common prefix rather than the specific instance.
            # e.g. ars_obj_00_dist_x_encode → ars_obj_dist_x_encode
            header, source = _rename_grouped_message_prefix(
                header, source, groups, selected_names
            )

            # Post-process: replace the group/message name prefix with the hex
            # frame-ID for entries that have the frame-ID prefix option enabled.
            # e.g. ars_obj_dist_x_encode → x400_dist_x_encode  (frame ID 0x400)
            if frame_id_prefix_items:
                header, source = _apply_frame_id_prefix(
                    header, source, groups, selected_names, frame_id_prefix_items
                )

            # Post-process: strip redundant signal suffix for grouped messages
            # (e.g. every signal in ARS_Obj_00 ends with _Obj_00 → strip it so
            # ars_obj_dist_x_obj_00_encode becomes ars_obj_dist_x_encode).
            if self._opt_strip_sig_suffix.get():
                header, source = _strip_redundant_signal_suffixes(
                    header, source, groups, selected_names
                )

            # Post-process: strip message/group name prefix from signal identifiers
            # (e.g. ars_obj_status_vehicle_platform_sig_decode → vehicle_platform_sig_decode).
            # Groups/messages with a hex frame-ID prefix are left untouched.
            if self._opt_strip_msg_name_prefix.get():
                header, source = _strip_message_name_prefix(
                    header, source, groups, selected_names, frame_id_prefix_items
                )

            # Post-process: inject frame-ID macros for all selected grouped messages
            # before any section-strip passes (strips will then apply uniformly).
            if self._opt_expand_group_ids.get():
                header = _inject_group_frame_ids(
                    header, groups, selected_names, ""
                )

            # Post-process: inject FRAME_ID_FIRST / FRAME_ID_LAST / FRAME_ID_COUNT
            # range macros for every group (always emitted when groups are present).
            header = _inject_group_range_macros(header, groups, selected_names)

            # Post-process: strip disabled header sections
            if self._opt_skip_length.get():
                header = _strip_section(header, "Frame lengths in bytes.")
            if self._opt_skip_extended.get():
                header = _strip_section(header, "Extended or standard frame types.")
            if self._opt_skip_cycle_time.get():
                header = _strip_section(header, "Frame cycle times in milliseconds.")
            if self._opt_skip_frame_names.get():
                header = _strip_section(header, "Frame Names.")
            if self._opt_skip_sig_names.get():
                header = _strip_section(header, "Signal Names.")
            if self._opt_skip_choices.get():
                header = _strip_section(header, "Signal choices.")
            if self._opt_skip_validate.get():
                header = _strip_validate_funcs(header)
                source = _strip_validate_funcs(source)

            # Post-process: replace inline bitshift helpers with a user include.
            bitshift_hdr = self._bitshift_header.get().strip()
            if bitshift_hdr:
                source = _replace_bitshift_funcs(source, bitshift_hdr)

            # Write output files (any conflict was already confirmed in _generate)
            out = Path(out_dir)
            out.mkdir(parents=True, exist_ok=True)

            for fname, content in [(h_name, header), (c_name, source)]:
                fpath = out / fname
                fpath.write_text(content, encoding="utf-8")
                self._log(f"  Written: {fpath}", tag="info")

            self._log(
                f"✅  Generation complete!  Output → {out_dir}", tag="success"
            )

        except Exception as exc:
            import traceback
            self._log(f"❌  {exc}", tag="danger")
            self._log(traceback.format_exc(), tag="danger")
        finally:
            self.after(0, self._generation_done)

    def _generation_done(self) -> None:
        self._progress.stop()
        self._progress.configure(bootstyle="secondary", mode="determinate")
        self._progress["value"] = 0
        self._gen_btn.configure(state="normal")

    # ── File dialogs ──────────────────────────────────────────────────────────

    def _browse_out_dir(self) -> None:
        path = filedialog.askdirectory(title="Select output directory")
        if path:
            self._out_path.set(path)

    # ── Settings persistence ──────────────────────────────────────────────────

    def _config_data(self) -> dict:
        """Collect all saveable UI state into a plain dict."""
        return {
            "out_path":           self._out_path.get(),
            "drv_name":           self._drv_name.get(),
            "sym_prefix":         self._sym_prefix.get(),
            "node_name":          self._node_name.get(),
            "bitshift_header":    self._bitshift_header.get(),
            # cantools options
            "opt_fp":             self._opt_fp.get(),
            "opt_bitfields":      self._opt_bitfields.get(),
            "opt_use_float":      self._opt_use_float.get(),
            "opt_use_round":      self._opt_use_round.get(),
            # output filter options
            "opt_skip_length":      self._opt_skip_length.get(),
            "opt_skip_extended":    self._opt_skip_extended.get(),
            "opt_skip_cycle_time":  self._opt_skip_cycle_time.get(),
            "opt_skip_frame_names": self._opt_skip_frame_names.get(),
            "opt_skip_sig_names":   self._opt_skip_sig_names.get(),
            "opt_skip_validate":    self._opt_skip_validate.get(),
            "opt_skip_choices":     self._opt_skip_choices.get(),
            # group / bitshift options
            "opt_expand_group_ids":       self._opt_expand_group_ids.get(),
            "opt_strip_sig_suffix":       self._opt_strip_sig_suffix.get(),
            "opt_strip_msg_name_prefix":  self._opt_strip_msg_name_prefix.get(),
            # last-used DBC file (so it can be offered as a default next time)
            "dbc_path":           self._dbc_path.get(),
        }

    def _save_config(self) -> None:
        """Write current UI state to the JSON config file."""
        try:
            CONFIG_PATH.write_text(
                json.dumps(self._config_data(), indent=2), encoding="utf-8"
            )
        except Exception:
            pass  # Never crash on save failure

    def _load_config(self) -> None:
        """Restore UI state from the JSON config file (if it exists)."""
        if not CONFIG_PATH.exists():
            return
        try:
            data: dict = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        except Exception:
            return  # Corrupt / incompatible file — silently ignore

        str_vars = {
            "out_path":        self._out_path,
            "drv_name":        self._drv_name,
            "sym_prefix":      self._sym_prefix,
            "node_name":       self._node_name,
            "bitshift_header": self._bitshift_header,
            "dbc_path":        self._dbc_path,
        }
        bool_vars = {
            "opt_fp":               self._opt_fp,
            "opt_bitfields":        self._opt_bitfields,
            "opt_use_float":        self._opt_use_float,
            "opt_use_round":        self._opt_use_round,
            "opt_skip_length":      self._opt_skip_length,
            "opt_skip_extended":    self._opt_skip_extended,
            "opt_skip_cycle_time":  self._opt_skip_cycle_time,
            "opt_skip_frame_names": self._opt_skip_frame_names,
            "opt_skip_sig_names":   self._opt_skip_sig_names,
            "opt_skip_validate":    self._opt_skip_validate,
            "opt_skip_choices":     self._opt_skip_choices,
            "opt_expand_group_ids":       self._opt_expand_group_ids,
            "opt_strip_sig_suffix":        self._opt_strip_sig_suffix,
            "opt_strip_msg_name_prefix":   self._opt_strip_msg_name_prefix,
        }

        for key, var in str_vars.items():
            if key in data and isinstance(data[key], str):
                var.set(data[key])

        for key, var in bool_vars.items():
            if key in data and isinstance(data[key], bool):
                var.set(data[key])

    def _on_close(self) -> None:
        """Save settings and close the window."""
        self._save_config()
        self.destroy()

    # ── Logging ───────────────────────────────────────────────────────────────

    def _log(self, message: str, tag: str = "") -> None:
        """Append *message* to the log pane (thread-safe)."""
        def _append() -> None:
            self._log_text.configure(state="normal")
            self._log_text.insert(END, message + "\n", (tag,) if tag else ())
            self._log_text.configure(state="disabled")
            self._log_text.see(END)

        self.after(0, _append)

    def _clear_log(self) -> None:
        self._log_text.configure(state="normal")
        self._log_text.delete("1.0", END)
        self._log_text.configure(state="disabled")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    app = CoderDbcGui()
    app.mainloop()


if __name__ == "__main__":
    main()
