#!/usr/bin/env python3
"""
C-CoderDBC GUI
==============
A graphical interface that generates C pack/unpack code from DBC CAN matrix
files directly through the *cantools* library — no external binary required.

Features
--------
* Load and preview any DBC file — messages and their signals shown in a tree.
* Select / deselect individual messages (or entire groups) to control which
  pack/unpack functions get generated.
* Auto-group similar messages by common name prefix + numeric suffix
  (e.g. 40 radar-object messages become one collapsible group).
* Live search / filter across message names.
* cantools generation options (floating-point, bit-fields, float vs double,
  rounding, per-node filtering) exposed as toggle switches.
* Output filter: optionally strip LENGTH / IS_EXTENDED / cycle-time #defines,
  frame/signal name macros, and validate (is_in_range) functions from the
  generated files.
* Generation runs in a background thread; a progress bar and coloured log
  pane keep you informed.

Requirements
------------
    pip install ttkbootstrap>=1.10.0 cantools

Usage
-----
    python3 gui.py
"""

import re
import sys
import threading
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

try:
    import ttkbootstrap as ttk
    from ttkbootstrap.constants import *
except ImportError:
    print(
        "ERROR: ttkbootstrap is required.\n"
        "Install it with:  pip install ttkbootstrap>=1.10.0",
        file=sys.stderr,
    )
    sys.exit(1)

try:
    import cantools
    import cantools.database
    from cantools.database.can.c_source import generate as _ct_generate
except ImportError:
    print(
        "ERROR: cantools is required.\n"
        "Install it with:  pip install cantools",
        file=sys.stderr,
    )
    sys.exit(1)

import tkinter as tk
from tkinter import filedialog, messagebox

# ── Constants ──────────────────────────────────────────────────────────────────

CHECKBOX_ON = "☑"
CHECKBOX_OFF = "☐"
CHECKBOX_PARTIAL = "⊟"

GROUP_MIN_SIZE = 2       # Minimum messages required to form an auto-group
APP_VERSION = "1.0"


# ── Generation helpers ─────────────────────────────────────────────────────────

def _strip_section(text: str, section_comment: str) -> str:
    """Remove a ``/* {section_comment} */`` block and its content.

    Each section in the cantools-generated header consists of a comment line
    followed by one or more ``#define`` lines and a blank-line separator.
    The entire block (comment + defines + trailing blank line) is replaced
    with a single blank line so surrounding sections remain readable.

    This relies on the fixed structure of ``cantools.database.can.c_source``
    HEADER_FMT where every section ends with exactly one blank line.
    """
    pattern = rf'/\* {re.escape(section_comment)} \*/\n(?:[^\n]+\n)*\n'
    return re.sub(pattern, '\n', text)


def _strip_validate_funcs(text: str) -> str:
    """Remove ``_is_in_range`` / ``_is_in_phys_range`` from header or source.

    **Header** pattern — a doxygen block immediately before a ``bool``
    declaration (as generated by cantools ``SIGNAL_DECLARATION_IS_IN_RANGE_FMT``
    and ``SIGNAL_DECLARATION_IS_IN_PHYS_RANGE_FMT``)::

        /**
         * Check that given signal is in allowed range.
         * ...
         */
        bool db_msg_sig_is_in_range(int16_t value);

    **Source** pattern — a bare function definition whose body contains at most
    one level of nested braces (the cantools-generated bodies are always a
    single ``return (expr);`` statement with no nested ``{}``)::

        bool db_msg_sig_is_in_range(int16_t value)
        {
            return ((value >= 0) && (value <= 100));
        }
    """
    # Header: doxygen comment block + bool declaration
    text = re.sub(
        r'/\*\*\n(?:\s*\*[^\n]*\n)*\s*\*/\nbool [^\n]+_is_in(?:_phys)?_range[^\n]+;\n',
        '',
        text,
    )
    # Source: function definition; allow one level of nested braces in the body
    # (cantools generates simple single-expression bodies, but be defensive)
    text = re.sub(
        r'bool [^\n]+_is_in(?:_phys)?_range[^\n]+\n\{(?:[^{}]|\{[^{}]*\})*\}\n',
        '',
        text,
    )
    return text


def _replace_identifier_prefix(
    header: str, source: str, drv_name: str, new_prefix: str
) -> Tuple[str, str]:
    """Replace (or strip) the cantools database-name identifier prefix.

    cantools prefixes every generated symbol with ``database_name``.  This
    function replaces that prefix with *new_prefix* in all identifiers of the
    generated header and source, then restores the include guard (which must
    stay derived from the output file name, not from the identifier prefix).

    *new_prefix* = ``""`` strips the prefix entirely so symbols become
    ``msgname_pack`` instead of ``dbname_msgname_pack``.
    """
    from_lower = re.escape(drv_name.lower()) + "_"
    from_upper = re.escape(drv_name.upper()) + "_"
    to_lower = (new_prefix.lower() + "_") if new_prefix else ""
    to_upper = (new_prefix.upper() + "_") if new_prefix else ""

    # Negative lookbehind: only replace at the start of an identifier token.
    pat_lower = r"(?<![a-zA-Z0-9_])" + from_lower
    pat_upper = r"(?<![a-zA-Z0-9_])" + from_upper

    for pat, repl in [(pat_upper, to_upper), (pat_lower, to_lower)]:
        header = re.sub(pat, repl, header)
        source = re.sub(pat, repl, source)

    # Restore the include guard.  cantools built it as
    # f'{database_name.upper()}_H'; after our replacement it is
    # f'{to_upper}H' (e.g. '' + 'H' = 'H' when prefix is blank).
    # We always want the guard to reflect the output file name (drv_name.h).
    orig_guard = drv_name.upper() + "_H"
    new_guard = to_upper + "H"
    if new_guard != orig_guard:
        header = header.replace(f"#ifndef {new_guard}\n", f"#ifndef {orig_guard}\n", 1)
        header = header.replace(f"#define {new_guard}\n", f"#define {orig_guard}\n", 1)
        header = header.replace(f"/* {new_guard} */",     f"/* {orig_guard} */")

    return header, source


# ── Auto-grouping ──────────────────────────────────────────────────────────────

def detect_groups(
    messages: List["cantools.database.Message"],
    min_size: int = GROUP_MIN_SIZE,
) -> Dict[str, List["cantools.database.Message"]]:
    """
    Detect groups of similarly-named messages.

    Messages whose names match ``<prefix><digits>`` (with an optional
    trailing underscore before the digits) are placed in a group named
    ``<prefix>``.  Groups with fewer than *min_size* members are kept as
    individual entries.

    Returns a plain dict: ``group_name → [Message, …]``.
    """
    _NUM_SUFFIX = re.compile(r"^(.*?)_?(\d+)$")
    bucket: Dict[str, List] = defaultdict(list)

    for msg in messages:
        m = _NUM_SUFFIX.match(msg.name)
        if m:
            prefix = m.group(1).rstrip("_") or msg.name
            bucket[prefix].append(msg)
        else:
            bucket[msg.name].append(msg)

    groups: Dict[str, List] = {}
    for prefix, msgs in bucket.items():
        if len(msgs) >= min_size:
            groups[prefix] = sorted(msgs, key=lambda x: x.frame_id)
        else:
            for msg in msgs:
                groups[msg.name] = [msg]

    return groups


# ── Main Application ──────────────────────────────────────────────────────────

class CoderDbcGui(ttk.Window):
    """
    Main application window for the C-CoderDBC GUI.

    Layout
    ------
    Left pane  — DBC tree (messages → signals) with checkbox selection,
                 search bar, and group controls.
    Right pane — Tabbed panel: Settings tab (paths, options, generate button)
                 and Output Log tab (coloured text console).
    """

    APP_TITLE = f"C-CoderDBC GUI  v{APP_VERSION}"

    def __init__(self) -> None:
        super().__init__(
            title=self.APP_TITLE,
            themename="darkly",
            size=(1200, 800),
            minsize=(860, 600),
        )

        # ── Application variables ───────────────────────────────────────────
        self._dbc_path = tk.StringVar()
        self._out_path = tk.StringVar()
        self._drv_name = tk.StringVar()
        self._sym_prefix = tk.StringVar()   # identifier prefix (blank = strip entirely)
        self._search_var = tk.StringVar()
        self._summary_var = tk.StringVar(value="No DBC file loaded")
        self._sel_summary = tk.StringVar(value="0 messages selected")

        # ── cantools generation options ─────────────────────────────────────
        self._opt_fp        = tk.BooleanVar(value=True)   # floating_point_numbers
        self._opt_bitfields = tk.BooleanVar(value=False)  # bit_fields
        self._opt_use_float = tk.BooleanVar(value=False)  # use_float
        self._opt_use_round = tk.BooleanVar(value=False)  # use_round
        self._node_name     = tk.StringVar(value="")      # node_name

        # ── Output filter toggles ────────────────────────────────────────────
        self._opt_skip_length      = tk.BooleanVar(value=False)
        self._opt_skip_extended    = tk.BooleanVar(value=False)
        self._opt_skip_cycle_time  = tk.BooleanVar(value=False)
        self._opt_skip_frame_names = tk.BooleanVar(value=False)
        self._opt_skip_sig_names   = tk.BooleanVar(value=False)
        self._opt_skip_validate    = tk.BooleanVar(value=False)

        # ── Internal state ──────────────────────────────────────────────────
        self._db: Optional[cantools.database.Database] = None
        self._messages: List[cantools.database.can.Message] = []
        self._groups: Dict[str, List[cantools.database.can.Message]] = {}
        # Selected message names (cantools message names are unique within a db)
        self._selected: Set[str] = set()
        # Maps tree-item IID → ("group", group_name) | ("msg", cantools Message)
        self._tree_items: Dict[str, Tuple[str, object]] = {}
        # Set in _on_tree_expand_collapse; read and cleared in _on_tree_click
        # to suppress checkbox toggling when the native indicator was clicked.
        self._suppress_next_click: bool = False

        # ── Build UI ────────────────────────────────────────────────────────
        self._build_ui()

    # ── UI Construction ──────────────────────────────────────────────────────

    def _build_ui(self) -> None:
        # Title bar
        hdr = ttk.Frame(self, padding=(10, 6))
        hdr.pack(fill=X)
        ttk.Label(
            hdr, text="C-CoderDBC", font=("", 18, "bold"), bootstyle="primary"
        ).pack(side=LEFT)
        ttk.Label(
            hdr, text="  DBC Preview & C Code Generator", bootstyle="secondary"
        ).pack(side=LEFT)

        ttk.Separator(self, orient=HORIZONTAL).pack(fill=X)

        # Main split: left = tree, right = settings+log
        paned = ttk.Panedwindow(self, orient=HORIZONTAL)
        paned.pack(fill=BOTH, expand=True, padx=6, pady=6)

        left = ttk.Frame(paned, padding=4)
        right = ttk.Frame(paned, padding=4)
        paned.add(left, weight=3)
        paned.add(right, weight=2)

        self._build_tree_panel(left)
        self._build_right_panel(right)

    # ── Left panel — DBC tree ────────────────────────────────────────────────

    def _build_tree_panel(self, parent: ttk.Frame) -> None:
        # Header
        hdr = ttk.Frame(parent)
        hdr.pack(fill=X, pady=(0, 4))
        ttk.Label(hdr, text="DBC Preview", font=("", 12, "bold")).pack(side=LEFT)
        ttk.Button(
            hdr, text="📂  Load DBC…", command=self._browse_dbc, bootstyle="primary"
        ).pack(side=RIGHT)

        # File path (read-only)
        ttk.Entry(
            parent, textvariable=self._dbc_path, state="readonly", bootstyle="secondary"
        ).pack(fill=X, pady=(0, 4))

        # Toolbar
        toolbar = ttk.Frame(parent)
        toolbar.pack(fill=X, pady=4)

        ttk.Label(toolbar, text="🔍").pack(side=LEFT)
        ttk.Entry(toolbar, textvariable=self._search_var, width=20).pack(
            side=LEFT, padx=(2, 8)
        )
        self._search_var.trace_add("write", lambda *_: self._apply_filter())

        ttk.Button(
            toolbar, text="Auto-Group", command=self._auto_group, bootstyle="info-outline"
        ).pack(side=LEFT, padx=2)
        ttk.Button(
            toolbar, text="Ungroup", command=self._ungroup, bootstyle="secondary-outline"
        ).pack(side=LEFT, padx=2)

        ttk.Separator(toolbar, orient=VERTICAL).pack(side=LEFT, fill=Y, padx=8)

        ttk.Button(
            toolbar, text="✓ All", command=self._select_all, bootstyle="success-outline"
        ).pack(side=LEFT, padx=2)
        ttk.Button(
            toolbar, text="✗ None", command=self._deselect_all, bootstyle="danger-outline"
        ).pack(side=LEFT, padx=2)

        # Summary label
        ttk.Label(
            parent, textvariable=self._summary_var, bootstyle="secondary"
        ).pack(anchor=W, pady=(2, 0))

        # Tree container
        tree_container = ttk.Frame(parent)
        tree_container.pack(fill=BOTH, expand=True, pady=(4, 0))

        # Increase Treeview row font from the default (~9 pt) to 11 pt so
        # message and signal names are more legible.
        self.style.configure("Treeview", font=("", 11))
        self.style.configure("Treeview.Heading", font=("", 10, "bold"))

        cols = ("sel", "dlc", "signals", "transmitter")
        self._tree = ttk.Treeview(
            tree_container,
            columns=cols,
            show="tree headings",
            selectmode="browse",
            bootstyle="primary",
        )
        self._tree.heading("#0", text="ID (hex)   Name")
        self._tree.heading(
            "sel", text=CHECKBOX_OFF,
            command=self._toggle_all_heading,
        )
        self._tree.heading("dlc", text="DLC")
        self._tree.heading("signals", text="Signals")
        self._tree.heading("transmitter", text="Transmitter")

        self._tree.column("#0", width=310, minwidth=180)
        self._tree.column("sel", width=30, minwidth=30, anchor=CENTER, stretch=False)
        self._tree.column("dlc", width=50, anchor=CENTER, minwidth=40)
        self._tree.column("signals", width=60, anchor=CENTER, minwidth=40)
        self._tree.column("transmitter", width=110, anchor=CENTER, minwidth=70)

        vsb = ttk.Scrollbar(tree_container, orient=VERTICAL, command=self._tree.yview)
        hsb = ttk.Scrollbar(tree_container, orient=HORIZONTAL, command=self._tree.xview)
        self._tree.configure(yscrollcommand=vsb.set, xscrollcommand=hsb.set)

        self._tree.grid(row=0, column=0, sticky="nsew")
        vsb.grid(row=0, column=1, sticky="ns")
        hsb.grid(row=1, column=0, sticky="ew")
        tree_container.rowconfigure(0, weight=1)
        tree_container.columnconfigure(0, weight=1)

        self._tree.bind("<ButtonRelease-1>", self._on_tree_click)
        # <<TreeviewOpen>> / <<TreeviewClose>> fire (between Button-1 and
        # ButtonRelease-1) only when the native expand/collapse indicator is
        # clicked.  We use them to suppress the checkbox toggle that would
        # otherwise fire in _on_tree_click.
        self._tree.bind("<<TreeviewOpen>>",  self._on_tree_expand_collapse)
        self._tree.bind("<<TreeviewClose>>", self._on_tree_expand_collapse)

    # ── Right panel — Settings + Log ─────────────────────────────────────────

    def _build_right_panel(self, parent: ttk.Frame) -> None:
        nb = ttk.Notebook(parent, bootstyle="primary")
        nb.pack(fill=BOTH, expand=True)

        settings_frame = ttk.Frame(nb, padding=10)
        nb.add(settings_frame, text=" ⚙  Settings ")
        self._build_settings_tab(settings_frame)

        log_frame = ttk.Frame(nb, padding=6)
        nb.add(log_frame, text=" 📋  Output Log ")
        self._build_log_tab(log_frame)

    def _build_settings_tab(self, parent: ttk.Frame) -> None:
        ttk.Label(
            parent, text="Code Generation Settings", font=("", 11, "bold")
        ).pack(anchor=W, pady=(0, 8))

        # Output directory
        ttk.Label(parent, text="Output directory").pack(anchor=W)
        out_row = ttk.Frame(parent)
        out_row.pack(fill=X, pady=(2, 8))
        ttk.Entry(out_row, textvariable=self._out_path).pack(
            side=LEFT, fill=X, expand=True
        )
        ttk.Button(out_row, text="…", width=3, command=self._browse_out_dir).pack(
            side=LEFT, padx=(4, 0)
        )

        # Driver name
        ttk.Label(parent, text="Driver name").pack(anchor=W)
        ttk.Entry(parent, textvariable=self._drv_name).pack(fill=X, pady=(2, 6))

        # Identifier prefix
        ttk.Label(
            parent, text="Identifier prefix  (blank = no prefix in symbol names)"
        ).pack(anchor=W)
        ttk.Entry(parent, textvariable=self._sym_prefix).pack(fill=X, pady=(2, 8))

        ttk.Separator(parent).pack(fill=X, pady=8)

        # ── cantools options ─────────────────────────────────────────────────
        ttk.Label(parent, text="cantools Options", font=("", 10, "bold")).pack(
            anchor=W, pady=(0, 4)
        )

        gen_opts = [
            (self._opt_fp,        "Floating-point encode/decode"),
            (self._opt_bitfields, "Bit fields in structs"),
            (self._opt_use_float, "Use float (not double)"),
            (self._opt_use_round, "Round encoded values (not truncate)"),
        ]
        for var, label in gen_opts:
            ttk.Checkbutton(
                parent, text=label, variable=var, bootstyle="primary-round-toggle"
            ).pack(anchor=W, pady=2)

        # Node name
        ttk.Label(parent, text="Node name (optional)").pack(anchor=W, pady=(6, 0))
        ttk.Entry(parent, textvariable=self._node_name).pack(fill=X, pady=(2, 0))

        ttk.Separator(parent).pack(fill=X, pady=8)

        # ── Output filter ────────────────────────────────────────────────────
        ttk.Label(parent, text="Output Filter", font=("", 10, "bold")).pack(
            anchor=W, pady=(0, 4)
        )

        filter_opts = [
            (self._opt_skip_length,      "Skip LENGTH #defines"),
            (self._opt_skip_extended,    "Skip IS_EXTENDED #defines"),
            (self._opt_skip_cycle_time,  "Skip cycle-time #defines"),
            (self._opt_skip_frame_names, "Skip frame-name macros"),
            (self._opt_skip_sig_names,   "Skip signal-name macros"),
            (self._opt_skip_validate,    "Skip validate functions (is_in_range)"),
        ]
        for var, label in filter_opts:
            ttk.Checkbutton(
                parent, text=label, variable=var, bootstyle="warning-round-toggle"
            ).pack(anchor=W, pady=2)

        ttk.Separator(parent).pack(fill=X, pady=8)

        ttk.Label(parent, textvariable=self._sel_summary, bootstyle="info").pack(
            anchor=W
        )

        self._gen_btn = ttk.Button(
            parent,
            text="⚡  Generate C Code",
            command=self._generate,
            bootstyle="success",
        )
        self._gen_btn.pack(fill=X, pady=(8, 4))

        self._progress = ttk.Progressbar(
            parent, bootstyle="secondary", mode="determinate"
        )
        self._progress.pack(fill=X, pady=(0, 4))
        # Starts at 0 (greyed/empty); becomes animated during generation.

    def _build_log_tab(self, parent: ttk.Frame) -> None:
        text_frame = ttk.Frame(parent)
        text_frame.pack(fill=BOTH, expand=True)

        self._log_text = tk.Text(
            text_frame,
            state="disabled",
            wrap="word",
            font=("Courier", 9),
            bg="#1e1e1e",
            fg="#d4d4d4",
            insertbackground="white",
            relief="flat",
        )
        vsb = ttk.Scrollbar(text_frame, orient=VERTICAL, command=self._log_text.yview)
        self._log_text.configure(yscrollcommand=vsb.set)
        self._log_text.grid(row=0, column=0, sticky="nsew")
        vsb.grid(row=0, column=1, sticky="ns")
        text_frame.rowconfigure(0, weight=1)
        text_frame.columnconfigure(0, weight=1)

        # Colour tags for log levels
        self._log_text.tag_config("warning", foreground="#f0ad4e")
        self._log_text.tag_config("success", foreground="#5cb85c")
        self._log_text.tag_config("danger",  foreground="#d9534f")
        self._log_text.tag_config("info",    foreground="#5bc0de")

        ttk.Button(
            parent, text="Clear Log", command=self._clear_log, bootstyle="secondary-outline"
        ).pack(anchor=E, pady=4)

    # ── DBC loading ──────────────────────────────────────────────────────────

    def _browse_dbc(self) -> None:
        docs = Path.home() / "Documents"
        initial = str(docs) if docs.is_dir() else str(Path.home())
        path = filedialog.askopenfilename(
            title="Select DBC file",
            initialdir=initial,
            filetypes=[("DBC files", "*.dbc"), ("All files", "*.*")],
        )
        if path:
            self._dbc_path.set(path)
            self._load_dbc(path)

    def _load_dbc(self, path: str) -> None:
        self._log(f"Loading: {path}", tag="info")
        try:
            self._db = cantools.database.load_file(path)
        except Exception as exc:
            self._log(f"ERROR parsing DBC file: {exc}", tag="danger")
            return

        self._messages = sorted(self._db.messages, key=lambda m: m.frame_id)
        self._selected = {m.name for m in self._messages}

        # Start with a flat (one group per message) layout
        self._groups = {msg.name: [msg] for msg in self._messages}
        self._populate_tree()
        self._update_summary()
        self._log(f"Loaded {len(self._messages)} message(s).", tag="success")

        # Auto-fill driver name and output dir from the filename
        stem = Path(path).stem
        if not self._drv_name.get():
            self._drv_name.set(stem)
        if not self._out_path.get():
            self._out_path.set(str(Path(path).parent / "gencode"))

    # ── Tree population ───────────────────────────────────────────────────────

    def _populate_tree(self) -> None:
        """Rebuild the entire Treeview from *self._groups*, respecting the search filter."""
        self._tree.delete(*self._tree.get_children())
        self._tree_items.clear()

        filter_text = self._search_var.get().lower()

        for group_name, msgs in sorted(
            self._groups.items(), key=lambda kv: min(m.frame_id for m in kv[1])
        ):
            visible = [
                m for m in msgs
                if not filter_text or filter_text in m.name.lower()
            ]
            if not visible:
                continue

            is_group = len(msgs) > 1

            if is_group:
                all_sel = all(m.name in self._selected for m in visible)
                any_sel = any(m.name in self._selected for m in visible)
                chk = (
                    CHECKBOX_ON if all_sel
                    else CHECKBOX_PARTIAL if any_sel
                    else CHECKBOX_OFF
                )
                min_id = min(m.frame_id for m in visible)
                total_sigs = sum(len(m.signals) for m in visible)
                g_iid = f"group::{group_name}"
                self._tree.insert(
                    "", END, iid=g_iid,
                    text=f"0x{min_id:03X}+  {group_name}  ({len(visible)} frames → 1 function set)",
                    values=(chk, "", total_sigs, ""),
                    open=False,
                    tags=("group",),
                )
                self._tree_items[g_iid] = ("group", group_name)
                for msg in visible:
                    self._insert_message(g_iid, msg)
            else:
                self._insert_message("", msgs[0])

        self._tree.tag_configure("group",  font=("", 11, "bold"))
        self._tree.tag_configure("signal", foreground="#888888")
        self._refresh_heading()

    def _insert_message(self, parent_iid: str, msg: "cantools.database.can.Message") -> None:
        selected = msg.name in self._selected
        chk = CHECKBOX_ON if selected else CHECKBOX_OFF
        m_iid = f"msg::{msg.frame_id}"
        sender = msg.senders[0] if msg.senders else ""
        self._tree.insert(
            parent_iid, END, iid=m_iid,
            text=f"0x{msg.frame_id:03X}  {msg.name}",
            values=(chk, msg.length, len(msg.signals), sender),
            tags=("msg",),
        )
        self._tree_items[m_iid] = ("msg", msg)

        for sig in msg.signals:
            s_iid = f"sig::{msg.frame_id}::{sig.name}"
            bo = "LE" if sig.byte_order == "little_endian" else "BE"
            vt = "S" if sig.is_signed else "U"
            self._tree.insert(
                m_iid, END, iid=s_iid,
                text=f"    {sig.name}  [{sig.start}|{sig.length}]",
                values=("", bo, vt, ""),
                tags=("signal",),
            )

    # ── Tree interaction ──────────────────────────────────────────────────────

    def _on_tree_expand_collapse(self, event: "tk.Event[ttk.Treeview]") -> None:
        """Suppress the checkbox toggle for the ButtonRelease-1 that follows
        a native expand/collapse indicator click.

        Tkinter fires <<TreeviewOpen>> / <<TreeviewClose>> (generated inside
        the widget's class binding for Button-1) *before* ButtonRelease-1
        reaches our handler.  Setting this flag here is therefore enough to
        reliably block the unwanted toggle, regardless of theme or platform.
        """
        self._suppress_next_click = True

    def _on_tree_click(self, event: "tk.Event[ttk.Treeview]") -> None:
        """Toggle message/group selection when the user clicks the name column."""
        region = self._tree.identify_region(event.x, event.y)
        if region not in ("tree", "cell"):
            return

        iid = self._tree.identify_row(event.y)
        if not iid or iid not in self._tree_items:
            return

        # React to clicks in the tree/name column (#0) or the checkbox column (#1).
        if self._tree.identify_column(event.x) not in ("#0", "#1"):
            return

        # Ignore clicks caused by the native expand/collapse indicator (▶ / ▼).
        # _on_tree_expand_collapse sets this flag via <<TreeviewOpen/Close>>,
        # which always fires before ButtonRelease-1 reaches us.
        if self._suppress_next_click:
            self._suppress_next_click = False
            return

        kind, data = self._tree_items[iid]
        if kind == "group":
            self._toggle_group(str(data))
        elif kind == "msg":
            self._toggle_message(data)  # type: ignore[arg-type]

        self._update_summary()

    def _toggle_message(self, msg: "cantools.database.can.Message") -> None:
        if msg.name in self._selected:
            self._selected.discard(msg.name)
        else:
            self._selected.add(msg.name)
        selected = msg.name in self._selected
        chk = CHECKBOX_ON if selected else CHECKBOX_OFF
        m_iid = f"msg::{msg.frame_id}"
        if self._tree.exists(m_iid):
            self._tree.set(m_iid, "sel", chk)
        self._refresh_parent_group(msg)
        self._refresh_heading()

    def _toggle_group(self, group_name: str) -> None:
        msgs = self._groups[group_name]
        all_sel = all(m.name in self._selected for m in msgs)
        if all_sel:
            for msg in msgs:
                self._selected.discard(msg.name)
        else:
            for msg in msgs:
                self._selected.add(msg.name)
        for msg in msgs:
            chk = CHECKBOX_ON if msg.name in self._selected else CHECKBOX_OFF
            m_iid = f"msg::{msg.frame_id}"
            if self._tree.exists(m_iid):
                self._tree.set(m_iid, "sel", chk)
        self._refresh_group_item(group_name)
        self._refresh_heading()

    def _refresh_group_item(self, group_name: str) -> None:
        g_iid = f"group::{group_name}"
        if not self._tree.exists(g_iid):
            return
        msgs = self._groups[group_name]
        all_sel = all(m.name in self._selected for m in msgs)
        any_sel = any(m.name in self._selected for m in msgs)
        chk = (
            CHECKBOX_ON if all_sel
            else CHECKBOX_PARTIAL if any_sel
            else CHECKBOX_OFF
        )
        n = len(msgs)
        min_id = min(m.frame_id for m in msgs)
        self._tree.set(g_iid, "sel", chk)

    def _refresh_parent_group(self, msg: "cantools.database.can.Message") -> None:
        for group_name, msgs in self._groups.items():
            if msg in msgs and len(msgs) > 1:
                self._refresh_group_item(group_name)
                break

    # ── Grouping ──────────────────────────────────────────────────────────────

    def _auto_group(self) -> None:
        if not self._messages:
            return
        self._groups = detect_groups(self._messages)
        self._populate_tree()
        n_groups = sum(1 for v in self._groups.values() if len(v) > 1)
        self._log(
            f"Auto-grouping complete: {n_groups} group(s) detected.", tag="info"
        )

    def _ungroup(self) -> None:
        if not self._messages:
            return
        self._groups = {msg.name: [msg] for msg in self._messages}
        self._populate_tree()

    # ── Selection helpers ─────────────────────────────────────────────────────

    def _select_all(self) -> None:
        self._selected = {m.name for m in self._messages}
        self._populate_tree()
        self._update_summary()

    def _deselect_all(self) -> None:
        self._selected.clear()
        self._populate_tree()
        self._update_summary()

    def _toggle_all_heading(self) -> None:
        """Toggle all messages on/off when the sel column heading checkbox is clicked."""
        if not self._messages:
            return
        all_sel = all(m.name in self._selected for m in self._messages)
        if all_sel:
            self._selected.clear()
        else:
            self._selected = {m.name for m in self._messages}
        self._populate_tree()
        self._update_summary()

    def _refresh_heading(self) -> None:
        """Update the sel column heading checkbox to reflect the current selection state."""
        if not self._messages:
            chk = CHECKBOX_OFF
        elif all(m.name in self._selected for m in self._messages):
            chk = CHECKBOX_ON
        elif any(m.name in self._selected for m in self._messages):
            chk = CHECKBOX_PARTIAL
        else:
            chk = CHECKBOX_OFF
        self._tree.heading("sel", text=chk)

    def _apply_filter(self) -> None:
        self._populate_tree()

    def _update_summary(self) -> None:
        total = len(self._messages)
        sel = sum(1 for m in self._messages if m.name in self._selected)
        func_sets = sum(
            1 for msgs in self._groups.values()
            if any(m.name in self._selected for m in msgs)
        )
        self._summary_var.set(f"{total} messages  |  {sel} selected")
        self._sel_summary.set(
            f"{sel} / {total} messages selected  →  {func_sets} function set(s) will be generated"
        )

    # ── Code generation ───────────────────────────────────────────────────────

    def _generate(self) -> None:
        if not self._messages:
            messagebox.showwarning("No DBC", "Please load a DBC file first.")
            return

        # For each group, emit only ONE representative message (the first selected
        # member).  This is the whole point of grouping: 111 radar frames with
        # identical signal layouts produce ONE pack/unpack function set, not 111.
        # Ungrouped (single-message) entries behave exactly as before.
        representatives: List["cantools.database.can.Message"] = []
        for msgs in sorted(self._groups.values(), key=lambda v: min(m.frame_id for m in v)):
            rep = next((m for m in msgs if m.name in self._selected), None)
            if rep is not None:
                representatives.append(rep)

        if not representatives:
            messagebox.showwarning(
                "Nothing Selected",
                "Select at least one message to generate code for.",
            )
            return

        out_dir = self._out_path.get().strip()
        drv_name = self._drv_name.get().strip()
        sym_prefix = self._sym_prefix.get().strip()

        if not out_dir:
            messagebox.showwarning("Missing", "Please specify an output directory.")
            return
        if not drv_name:
            messagebox.showwarning("Missing", "Please specify a driver name.")
            return

        # Check for file conflicts on the main thread, before starting the worker.
        out = Path(out_dir)
        h_name = f"{drv_name}.h"
        c_name = f"{drv_name}.c"
        conflicts = [f for f in (h_name, c_name) if (out / f).exists()]
        if conflicts:
            names = "\n  • ".join(conflicts)
            if not messagebox.askyesno(
                "Files Already Exist",
                f"The following file(s) already exist in:\n{out_dir}\n\n  • {names}\n\nOverwrite?",
                parent=self,
            ):
                return

        self._gen_btn.configure(state="disabled")
        self._progress.configure(bootstyle="success-striped", mode="indeterminate")
        self._progress.start(10)
        threading.Thread(
            target=self._run_generation,
            args=(representatives, out_dir, drv_name, sym_prefix),
            daemon=True,
        ).start()

    def _run_generation(
        self,
        selected: List["cantools.database.can.Message"],
        out_dir: str,
        drv_name: str,
        sym_prefix: str,
    ) -> None:
        try:
            # Build a filtered in-memory database from the selected messages.
            filtered_db = cantools.database.Database(messages=selected)
            h_name = f"{drv_name}.h"
            c_name = f"{drv_name}.c"
            node = self._node_name.get().strip() or None

            self._log(
                f"Generating C code for {len(selected)} function set(s)…", tag="info"
            )

            header, source, _, _ = _ct_generate(
                filtered_db,
                drv_name,
                h_name,
                c_name,
                f"{drv_name}_fuzzer.c",
                floating_point_numbers=self._opt_fp.get(),
                bit_fields=self._opt_bitfields.get(),
                use_float=self._opt_use_float.get(),
                node_name=node,
                use_round=self._opt_use_round.get(),
            )

            # Post-process: replace identifier prefix if the user specified one
            # different from the driver name (or blank = strip entirely).
            if sym_prefix != drv_name:
                header, source = _replace_identifier_prefix(
                    header, source, drv_name, sym_prefix
                )

            # Post-process: strip disabled header sections
            if self._opt_skip_length.get():
                header = _strip_section(header, "Frame lengths in bytes.")
            if self._opt_skip_extended.get():
                header = _strip_section(header, "Extended or standard frame types.")
            if self._opt_skip_cycle_time.get():
                header = _strip_section(header, "Frame cycle times in milliseconds.")
            if self._opt_skip_frame_names.get():
                header = _strip_section(header, "Frame Names.")
            if self._opt_skip_sig_names.get():
                header = _strip_section(header, "Signal Names.")
            if self._opt_skip_validate.get():
                header = _strip_validate_funcs(header)
                source = _strip_validate_funcs(source)

            # Write output files (any conflict was already confirmed in _generate)
            out = Path(out_dir)
            out.mkdir(parents=True, exist_ok=True)

            for fname, content in [(h_name, header), (c_name, source)]:
                fpath = out / fname
                fpath.write_text(content, encoding="utf-8")
                self._log(f"  Written: {fpath}", tag="info")

            self._log(
                f"✅  Generation complete!  Output → {out_dir}", tag="success"
            )

        except Exception as exc:
            import traceback
            self._log(f"❌  {exc}", tag="danger")
            self._log(traceback.format_exc(), tag="danger")
        finally:
            self.after(0, self._generation_done)

    def _generation_done(self) -> None:
        self._progress.stop()
        self._progress.configure(bootstyle="secondary", mode="determinate")
        self._progress["value"] = 0
        self._gen_btn.configure(state="normal")

    # ── File dialogs ──────────────────────────────────────────────────────────

    def _browse_out_dir(self) -> None:
        path = filedialog.askdirectory(title="Select output directory")
        if path:
            self._out_path.set(path)

    # ── Logging ───────────────────────────────────────────────────────────────

    def _log(self, message: str, tag: str = "") -> None:
        """Append *message* to the log pane (thread-safe)."""
        def _append() -> None:
            self._log_text.configure(state="normal")
            self._log_text.insert(END, message + "\n", (tag,) if tag else ())
            self._log_text.configure(state="disabled")
            self._log_text.see(END)

        self.after(0, _append)

    def _clear_log(self) -> None:
        self._log_text.configure(state="normal")
        self._log_text.delete("1.0", END)
        self._log_text.configure(state="disabled")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    app = CoderDbcGui()
    app.mainloop()


if __name__ == "__main__":
    main()
